Draft: [IMP] open_academy: Creation of course model T#59081
JesusValdez96/open_academy pull request #1
Opened 2022-07-21 18:49 UTC by JesusValdez96

Exercise "Define a model".

2022-07-21 18:56 UTC, andreaarce commented
Please on the PR description add more information about for what is this change and not the description of the exercise.

The same applies to the commit. 

Also to the python files add a new line at the end of the file

2022-07-21 18:56 UTC, andreaarce commented
@CarmenMiranda Please review

2022-07-21 19:08 UTC, CarmenMiranda commented
Hi @andreaarce I have the same comments that you said already, the new lines at the end in the files, and a better description in the commit, just one other thing is that the name should be `[ADD]` instead of `[IMP]` because all the things that are being done are adding new files

2022-07-21 22:22 UTC, JesusValdez96 commented
Please review @andreaarce, @CarmenMiranda

2022-07-21 23:40 UTC, CarmenMiranda requested changes
Just another new line that is missing, also, can you change the name of the PR with the ADD, and if possible in the commit add a link to the exercise

Also, update the description in the PR with the message that you put in the commit.

2022-07-21 23:40 UTC, CarmenMiranda commented on .gitignore
> +.pylintrc-optional
Missing new line at the end of the file

2022-07-22 00:30 UTC, JesusValdez96 commented
Thank you!
Changes made @andreaarce, @CarmenMiranda

2022-07-22 16:06 UTC, CarmenMiranda approved these changes
Technically LGTM 👍🏼  @JesusValdez96 Just remove the draft in the name of the PR and it will be ready to merge @andreaarce

2022-07-22 16:40 UTC, merged