Draft: [IMP] open_academy: Add taken_seats computed field T#59081
JesusValdez96/open_academy pull request #10
Opened 2022-08-04 20:58 UTC by JesusValdez96

- Add taken_seats field to the session model and views to show the computed percentage of taken seats as a progress bar.
- Add a dependency to taken_seats with number_of_seats and attendee_ids to recompute its value on change.
- Change groups in session form view to use only two groups to all fields instead of a group for each two fields.

From exercise "Default values":
- Add today as default value to start_date field in session model.
- Add active field with True as default value to the session model, Tree and Form views.

Taken_seats and active status in Session Tree View: 
![session tree view](https://user-images.githubusercontent.com/108701886/182949939-bb5bcc56-da5d-4303-ad94-ad4839f7f9a7.png)

Default values in start_date and active status in the Session Form View:
![new session](https://user-images.githubusercontent.com/108701886/182950349-0d3738dd-53e4-40b4-861f-6fc565b59d09.png)

Computed value of taken_seats: 
![sesssion form view](https://user-images.githubusercontent.com/108701886/182950902-c17bb2d9-30ba-4da9-9aae-e845a9f46c14.png)

Link to exercises: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#computed-fields-and-default-values

2022-08-04 21:01 UTC, JesusValdez96 commented
Please review @andreaarce, @CarmenMiranda

2022-08-04 22:53 UTC, CarmenMiranda requested changes

2022-08-04 22:53 UTC, CarmenMiranda commented on open_academy/models/session.py
> +    active = fields.Boolean(default=True)
Add it at the beginning (below name) 🙈

2022-08-04 22:53 UTC, CarmenMiranda commented on open_academy/models/session.py
> +    def _compute_taken_seats(self):
As you are adding depends, I would recommend adding the attribute `store=True` to the field `taken_seats` this will help when showing the field in the tree view, it will avoid performance issues

2022-08-04 22:53 UTC, CarmenMiranda commented on open_academy/models/session.py
> +                record.taken_seats = 0
Try to avoid multiple sets, this can be done like this:
```python
taken_seats = 0
if record.number_of_seats > 0:
    taken_seats = len(record.attendee_ids) * 100 / record.number_of_seats
record.taken_seats = taken_seats
```

Also, this will help when you have to add tests, you will avoid covering one line (`else`)🙈

2022-08-04 22:59 UTC, andreaarce commented on open_academy/models/session.py
> +    active = fields.Boolean(default=True)
Do you mean "is" ?

2022-08-04 23:02 UTC, CarmenMiranda commented on open_academy/models/session.py
> +    active = fields.Boolean(default=True)
No, just moving the line, so `active` can be the second field, is more a nitpick 🙈

2022-08-05 18:09 UTC, JesusValdez96 commented
Changes made @andreaarce, @CarmenMiranda

2022-08-08 16:34 UTC, CarmenMiranda approved these changes
@andreaarce This LGTM 👍🏼

2022-08-08 19:59 UTC, merged