Draft: [IMP] open_academy: Warning on invalid values T#59081
JesusValdez96/open_academy pull request #11
Opened 2022-08-05 22:35 UTC by JesusValdez96

- Add Onchange method to validate that the number of seats is not negative and that the number of attendees does not exceed the number of seats. 
If validations fail, a warning is returned.

Negative value in number_of_seats field:
![negative value](https://user-images.githubusercontent.com/108701886/183219516-37f81d30-9853-4644-8896-dc17f4f92e6a.png)

Number of Attendees exceed Number of Seats:
![attendees](https://user-images.githubusercontent.com/108701886/183219548-40d2e076-7813-4361-9b24-de4852a05949.png)

Link to exercise: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#onchange

2022-08-05 22:36 UTC, JesusValdez96 commented
Please review @andreaarce, @CarmenMiranda :see_no_evil:

2022-08-08 16:44 UTC, CarmenMiranda requested changes
@JesusValdez96 Rebase with what you have in PR #10 so that you have the SHA of the commit in there and in the commit "[IMP] open_academy: Warning on invalid values" of this PR only has what is added in here and not part of the other PR

Also,  the name of the commit should be "[ADD]" instead of "[IMP]"

2022-08-08 20:00 UTC, andreaarce commented
PR #10 Merged please rebase

2022-08-08 22:46 UTC, JesusValdez96 commented
I made the rebase.
Please review again @andreaarce, @CarmenMiranda

2022-08-08 23:07 UTC, CarmenMiranda approved these changes
@andreaarce Technically LGTM 👍🏼

2022-08-09 15:18 UTC, merged