[ADD] open_academy: Add Manager group and record rule T#59081
JesusValdez96/open_academy pull request #14
Opened 2022-08-12 23:51 UTC by JesusValdez96

- Add Manager group to grant full access to all models to users in this group
![manager group](https://user-images.githubusercontent.com/108701886/184457707-b27a404c-c551-454e-9409-93135868a7fa.png)

- Add only read perms to all users
![read perm](https://user-images.githubusercontent.com/108701886/184457750-4acb387a-49cc-4af8-babe-5c37c8500c18.png)

- Add record rule "course_rule_manager" to restricts write and unlink accesses to the responsible of a course.
![record rule](https://user-images.githubusercontent.com/108701886/184457753-93bfc712-7c4e-4245-8623-0721cbb21ab2.png)

Link to exercises: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#security

2022-08-13 00:01 UTC, JesusValdez96 commented
Please review @andreaarce, @CarmenMiranda

2022-08-15 17:14 UTC, andreaarce commented on open_academy/security/course_security.xml
> +    <record id="course_rule_manager" model="ir.rule">
For me, it's better to add the rule as the first word on the id as rule_course_manager

2022-08-15 17:14 UTC, andreaarce commented on open_academy/security/course_security.xml
> +        <field name="name">Courses can only be written or unlinked by the responsible</field>
I think a better name could be Write or Delete responsible own courses

2022-08-15 21:53 UTC, andreaarce commented on open_academy/security/course_security.xml
> +    <record id="course_group_manager" model="res.groups">
Please move this to a new file in security

2022-08-15 23:41 UTC, CarmenMiranda requested changes

2022-08-15 23:41 UTC, CarmenMiranda commented on open_academy/security/course_security.xml
> +    <record id="course_group_manager" model="res.groups">
I agree with Andrea, try to have a file for each model

2022-08-15 23:41 UTC, CarmenMiranda commented on open_academy/security/course_security.xml
> +    <record id="course_rule_manager" model="ir.rule">
I agree with Andrea

2022-08-15 23:41 UTC, CarmenMiranda commented on open_academy/security/course_security.xml
> +</odoo>
Missing new line

2022-08-16 21:22 UTC, JesusValdez96 commented
I got confused, it's not a group for courses, it's a manager group for the whole module, that's why I renamed it to `open_academy_group_manager` and create only one file "res_groups.xml" with this new group.
Please review again @andreaarce, @CarmenMiranda

2022-08-16 23:08 UTC, CarmenMiranda reviewed
I recommend renaming the file `couse_security.xml` to `ir_rule.xml`
What do you think @andreaarce ??

2022-08-17 16:46 UTC, JesusValdez96 commented
File renamed
Please review again @andreaarce, @CarmenMiranda :smiley:

2022-08-17 16:48 UTC, andreaarce commented
LGTM @CarmenMiranda

2022-08-17 19:57 UTC, CarmenMiranda approved these changes
@andreaarce Technically LGTM 👍🏼

2022-08-17 21:16 UTC, merged