[ADD] open_academy: Add Session report view T#59081
JesusValdez96/open_academy pull request #17
Opened 2022-09-05 21:24 UTC by JesusValdez96

- Add report view for session model to display session name, start and end date, and the list of attendees.
![menu report](https://user-images.githubusercontent.com/108701886/188513107-97cbceea-eaba-4b0a-a896-cbe49bd6ac4f.png)

- Update es.po translation file to include strings from report functionality.

Test Session Report:
[Test session.pdf](https://github.com/JesusValdez96/open_academy/files/9492005/Test.session.pdf)

Link to exercise: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#printed-reports

2022-09-05 21:25 UTC, JesusValdez96 commented
@andreaarce Please review :speak_no_evil:

2022-09-05 22:05 UTC, andreaarce commented on open_academy/i18n/es.po
> +msgstr "Fecha de fin"
Don't forget that the msgid need to be the same as msgtr
```suggestion
msgstr "<strong>Fecha de fin:</strong>"
```
If you don't do this, the term will not get the strong properties

2022-09-05 22:05 UTC, andreaarce commented on open_academy/i18n/es.po
> +msgstr "Fecha de inicio"
same as above

2022-09-05 22:05 UTC, andreaarce commented on open_academy/i18n/es.po
> +msgstr "Correo"
```suggestion
msgstr "Correo electrónico"
```

2022-09-05 22:05 UTC, andreaarce commented
@CarmenMiranda Please review

2022-09-05 22:09 UTC, CarmenMiranda requested changes

2022-09-05 22:09 UTC, CarmenMiranda commented on open_academy/i18n/es.po
> +"POT-Creation-Date: 2022-09-05 19:15+0000\n"
You can update the Revision date, but you don't need to update the Creation date

2022-09-05 22:09 UTC, CarmenMiranda commented on open_academy/i18n/es.po
> +msgstr "Fecha de fin"
Missing `strong` tags

2022-09-05 22:09 UTC, CarmenMiranda commented on open_academy/i18n/es.po
> +msgstr "Fecha de inicio"
Missing `strong` tags

2022-09-05 22:09 UTC, CarmenMiranda commented on open_academy/report/session_report.xml
> +                            <tr t-foreach="attendees" t-as="attendee">
You don't need to set another variable
```suggestion
                            <tr t-foreach="session.mapped('attendee_ids')" t-as="attendee">
```

2022-09-06 20:50 UTC, JesusValdez96 commented
Please review again @CarmenMiranda, @andreaarce

2022-09-06 21:18 UTC, andreaarce approved these changes

2022-09-07 16:52 UTC, CarmenMiranda approved these changes
@andreaarce Technically LGTM 👍🏼

2022-09-07 18:22 UTC, merged