Draft: [ADD] open_academy: Added course demo data T#59081
JesusValdez96/open_academy pull request #2
Opened 2022-07-22 23:45 UTC by JesusValdez96

Creation of demo data for the course model
Link to exercise: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#data-files

2022-07-22 23:57 UTC, JesusValdez96 commented
Please review @andreaarce

2022-07-25 15:56 UTC, andreaarce commented
@CarmenMiranda Please help me with the review

2022-07-25 16:59 UTC, CarmenMiranda requested changes
I just add  a comment, and I going to recommend or do 2 commits, the first one with the readme and the fix with the pre-commit, and the second commit with the demo, or the other option is to add those changes in the description of the commit

@andreaarce What do you think about the commits?

2022-07-25 16:59 UTC, CarmenMiranda commented on open_academy/__manifest__.py
> +        "base"
I recommend adding a comma here, so when another dependency is added just one line is added and not one added and another is modified

2022-07-25 17:24 UTC, andreaarce commented on open_academy/__manifest__.py
> +        "base"
I prefer one commit with the changes in the description

2022-07-25 17:26 UTC, andreaarce commented on open_academy/__manifest__.py
> +    "category": "Uncategorized",
Change the category to Customizations

2022-07-25 17:27 UTC, andreaarce commented on open_academy/__manifest__.py
> +        "security/ir.model.access.csv"
Also the same comment than @CarmenMiranda please add a comma to the final line

2022-07-25 17:27 UTC, andreaarce commented on open_academy/__manifest__.py
> +        "demo/course_demo.xml"
Add a comma

2022-07-25 17:29 UTC, andreaarce commented on open_academy/security/ir.model.access.csv
> +access_open_academy_open_academy,open_academy.open_academy,model_open_academy_open_academy,base.group_user,1,1,1,1
This line has no effect on the project the open_academy model doesn't exist please replace to the course model and change all the related references

2022-07-25 17:34 UTC, CarmenMiranda commented on open_academy/security/ir.model.access.csv
> +access_open_academy_open_academy,open_academy.open_academy,model_open_academy_open_academy,base.group_user,1,1,1,1
Oh, I didn't know that the model didn't exist 🙈

2022-07-25 23:29 UTC, JesusValdez96 commented
Please review again @andreaarce, @CarmenMiranda

2022-07-26 00:54 UTC, CarmenMiranda approved these changes
@andreaarce Technically LGTM 👍🏼

2022-07-26 00:54 UTC, CarmenMiranda commented
@JesusValdez96 Just remove the draft state of the merge 😄

2022-07-26 00:56 UTC, JesusValdez96 commented
Removed. Thanks! @CarmenMiranda

2022-07-26 18:14 UTC, merged