[IMP] open_academy: Relations between course and session T#59081
JesusValdez96/open_academy pull request #7
Opened 2022-08-01 19:54 UTC by JesusValdez96

- Add next relation fields as in the exercise "Many2one relations":
- Add Many2one relation as "course" field between session and course.
- Add Many2one field in session model to add a instructor field related to partners model.
- Add Many2one relation in course model with users to add responsible user field.

- Add One2many field "sessions" to reflect the relation between courses and sessions as exercise "Inverse one2many relations" indicates.

- Add Attendees Many2many field at session model as exercise "Multiple many2many relations".

- Add Responsible user field to Tree and Form views of course view.
- Add new fields to Session Tree view.
- Add Session Form view.

Responsible user in Course Tree view:
![responsible field](https://user-images.githubusercontent.com/108701886/182231252-611977a4-6a21-47a3-b33d-ea82d71a4841.png)

Responsible user and Sessions in Course Form view:
![session field in course](https://user-images.githubusercontent.com/108701886/182232949-1a89b2a2-34b5-4d74-881a-4d3797ea07e6.png)

Session Tree view:
![session tree view](https://user-images.githubusercontent.com/108701886/182233030-74b200a9-0b10-4d39-9aca-5ce6105aef3b.png)

Session Form view:
![session form view](https://user-images.githubusercontent.com/108701886/182233060-d603eb05-cc9d-4c45-8473-c644edced31b.png)

Link to exercises: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#relational-fields

2022-08-01 20:14 UTC, JesusValdez96 commented
Please review @andreaarce, @CarmenMiranda

2022-08-01 21:56 UTC, CarmenMiranda requested changes

2022-08-01 21:56 UTC, CarmenMiranda commented on open_academy/models/course.py
> +    responsible_user = fields.Many2one("res.users")
The name of fields m2o, o2m, and m2m, need to include `_id` (m2o) or `_ids` (om2, m2m) at the end
In the case with `_ids` we need to include the string with the plural


`responsible_user_id = fields.Many2one("res.users")`
This comment applies to this file and the session file

2022-08-01 21:56 UTC, CarmenMiranda commented on open_academy/models/course.py
> +    sessions = fields.One2many("session", "course")
```python
session_ids = fields.One2many(
    "session", "course_id",
    string="Sessions",
)
```

2022-08-01 23:22 UTC, andreaarce commented on open_academy/models/session.py
> +    instructor = fields.Many2one("res.partner")
Please here apply the comments of @CarmenMiranda about the name of the field for m2o for the course and attendees fields too

2022-08-02 18:37 UTC, JesusValdez96 commented
Please review again @CarmenMiranda, @andreaarce

2022-08-02 19:14 UTC, CarmenMiranda approved these changes
Technically LGTM 👍🏼

2022-08-02 20:12 UTC, merged