[ADD] open_academy: Add inherited partner model T#59081
JesusValdez96/open_academy pull request #8
Opened 2022-08-02 23:38 UTC by JesusValdez96

- Add instructor and session_ids fields to partner model through inheritance.
- Add inherited partner view to show if the partner is instructor and the sessions they will attend.

![Captura](https://user-images.githubusercontent.com/108701886/182494230-766e9641-46fe-4365-8248-46e244c055e2.png)

Link to exercise: https://www.odoo.com/documentation/15.0/developer/howtos/backend.html#view-inheritance

2022-08-02 23:38 UTC, JesusValdez96 commented
Please review @andreaarce, @CarmenMiranda

2022-08-03 15:37 UTC, andreaarce commented
LGTM

2022-08-03 16:14 UTC, CarmenMiranda requested changes

2022-08-03 16:14 UTC, CarmenMiranda commented on open_academy/__manifest__.py
> +        "views/partner_views.xml",
Rename it to `res_partner_views`

2022-08-03 16:14 UTC, CarmenMiranda commented on open_academy/models/__init__.py
> +from . import partner
Rename it to `res_partner`

2022-08-03 16:14 UTC, CarmenMiranda commented on open_academy/models/partner.py
> +    instructor = fields.Boolean()
I recommend naming it as `is_instructor`

2022-08-03 17:18 UTC, JesusValdez96 commented
Changes made @CarmenMiranda, @andreaarce

2022-08-03 17:47 UTC, CarmenMiranda approved these changes
@andreaarce Technically LGTM 👍🏼

2022-08-03 17:58 UTC, merged